### ISSUE TITLE
The installation instructions given in the README file do not work.

### ISSUE THREAD

**Issue by antoinecarme** [antoinecarme/sklearn_model_explanation#11]
The installation instructions given in the README file do not work.

''' 
pip3 install --upgrade git+git://github.com/antoinecarme/sklearn_explain.git
Collecting git+git://github.com/antoinecarme/sklearn_explain.git
  Cloning git://github.com/antoinecarme/sklearn_explain.git to /tmp/pip-t8fwk9sw-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-t8fwk9sw-build/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-t8fwk9sw-build/

'''

Please add a proper installer

**Comment by antoinecarme** [comment]
Fixed
